version: '3.3'

volumes:
    pg_data:
    static:
    media:

services:
  
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    container_name: foodgram-back
    image: banan4k2002/foodgram_backend:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    container_name: foodgram-front
    image: banan4k2002/foodgram_frontend:latest
    volumes:
      - static:/app/result_build/build/.
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./infra/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - media:/media
