version: '3.3'

volumes:
    pg_data:
    static:
    media:

services:
  
  db:
    container_name: foodgram-db
    image: postgres:13
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  backend:
    container_name: foodgram-back
    build: ../backend
    env_file: ../.env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - static:/backend_static
      - media:/media
  frontend:
    container_name: foodgram-front
    build: ../frontend
    volumes:
      - static:/app/result_build/build/.
  nginx:
    container_name: foodgram-proxy
    build: .
    ports:
      - "8080:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - static:/usr/share/nginx/html/
      - media:/media
