# Generated by Django 4.2.13 on 2024-06-20 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortlink", "0007_alter_shortlink_id"),
        ("recipes", "0002_alter_favorite_recipe_alter_favorite_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="short_link",
            field=models.OneToOneField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="shortlink.shortlink",
            ),
            preserve_default=False,
        ),
    ]
