# Generated by Django 4.2.13 on 2024-06-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortlink", "0007_alter_shortlink_id"),
        ("recipes", "0003_recipe_short_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="short_link",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shortlink.shortlink",
            ),
        ),
    ]
