# Generated by Django 4.2.13 on 2024-06-24 13:18

import shortuuidfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'recipes',
            '0003_alter_favorite_options_alter_ingredient_options_and_more',
        ),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_link',
            field=shortuuidfield.fields.ShortUUIDField(
                blank=True, editable=False, max_length=22, unique=True
            ),
        ),
    ]
