# Generated by Django 4.2.13 on 2024-06-25 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0004_recipe_short_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={
                "ordering": ("-id",),
                "verbose_name": "рецепт",
                "verbose_name_plural": "Рецепты",
            },
        ),
    ]
