# Generated by Django 4.2.13 on 2024-06-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(
                max_length=32, unique=True, verbose_name="Название"
            ),
        ),
    ]
