# Generated by Django 4.2.13 on 2024-06-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "users",
            "0002_user_avatar_alter_user_email_alter_user_first_name_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(upload_to="users", verbose_name="Аватар"),
        ),
    ]
