# Generated by Django 4.2.13 on 2024-06-22 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "подписка",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
