# Generated by Django 4.2.13 on 2024-06-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_subscription_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "verbose_name": "подписку",
                "verbose_name_plural": "Подписки",
            },
        ),
    ]
